apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: czwnkm1gv-dotnet-basic
  janus-idp.io/tekton: czwnkm1gv-dotnet-basic
  backstage.io/kubernetes-id: czwnkm1gv-dotnet-basic
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: czwnkm1gv-dotnet-basic
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
